### ISSUE TITLE
Reduce library interface

### ISSUE THREAD

**Issue by tagatac** [adrium/goheif#1]
At the moment, the sample usage `heic2jpg` is nearly 100 lines. Since this is a typical usage, it would be great to put this functionality behind a couple of exported functions, e.g.
- `heif.HEIC2JPG(src, dstDir string) error`
- `heif.NewWriterExif(w io.Writer, exif []byte) (io.Writer, error)`

It's easy enough convert `heic2jpg` to these functions (e.g. https://github.com/tagatac/bagoup/blob/8900625c378ba656986e993177a4d5fee6d19ed9/opsys/heic2jpg.go). I'll post a PR soon if no one beats me to it.

**Comment by adrium** [comment]
I prefer not to change the structure of the original code. Also, the library is about decoding files and should not make an assumption about the user's intention. I will leave it as is.
